# Generated by Django 5.1.2 on 2024-10-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_program_topic_alter_program_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='title',
            new_name='name',
        ),
    ]
